### ISSUE TITLE
onf-ethernet-conditional-packages instead of onf-ethernet-conditional-package

### ISSUE THREAD

**Issue by demx8as6** [Melacon/WirelessTransportEmulator#3]
Please replace in the LTP(ETH).LP extensions

urn:onf:params:xml:ns:yang:onf-ethernet-conditional-package?module=onf-ethernet-conditional-package

by

urn:onf:params:xml:ns:yang:onf-ethernet-conditional-packages?module=onf-ethernet-conditional-packages

(wrong spec ;( )

**Comment by alexandrustancu** [comment]
Done :)
